### ISSUE TITLE
我用这个库调用so文件，会报cgo错误，有没办法避免这个错误

### ISSUE THREAD

**Issue by 601630051** [ying32/dylib#5]
我在调用cgo的时候，报这个错误，有没办法在go里面返回错误信息，不好把整个错误影响程序的执行。

goroutine 1 [running]:
mprtmp/dylib.(*LazyProc).CallOriginal.func4(0xc0000c0180?, {0xc00004fd48?, 0xc00004fd50?, 0xc00004fd58?})
        /home/go/test1/mprtmp/dylib/dylib_posix.go:282 +0x8a
mprtmp/dylib.(*LazyProc).CallOriginal(0xc0000c0180, {0xc00004fd48, 0x3, 0x3})
        /home/go/test1/mprtmp/dylib/dylib_posix.go:282 +0xd5
mprtmp/dylib.(*LazyDLL).call(0x4978c5?, 0x4970ba?, {0xc00004fd48?, 0xc00004fd50?, 0xc00004fd58?})
        /home/go/test1/mprtmp/dylib/dylib_posix.go:190 +0x9c5
mprtmp/dylib.(*LazyProc).Call(...)

**Comment by ying32** [comment]
那要看是什么错误了 如果是dll中的异常，是捕捉不了的，会直接造成程序崩溃。如果是go里面的你得再封装下用`recover`捕捉。
